services:
  - type: web
    name: routing-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SELF_URL
        value: https://routing-server-8yxk.onrender.com
    healthCheckPath: /healthz
    autoDeploy: true
