services:
  - type: web
    name: routing-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SELF_URL
        value: https://routing-server-8yxk.onrender.com
    healthCheckPath: /healthz
    autoDeploy: true
